[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_INCLUDE = "optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
